### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by nathanathan** [turbomaze/JS-Fourier-Image-Analysis#1]
Hi, I'd like to use this project in a hybrid image maker. I've started building it here (but I haven't added any code yet): https://github.com/nathanathan/hybrid-image-maker
If you don't mind me using your code to do the filtering could you add a license?
Thanks,
-Nathan

**Comment by turbomaze** [comment]
Hi Nathan,

I just added an MIT license. Good luck on your project!

Anthony

**Comment by waldyrious** [comment]
@turbomaze maybe close this issue? :)
