### ISSUE TITLE
what is the fun of "lol c++" about this line?

### ISSUE THREAD

**Issue by naiteluo** [turbomaze/JS-Fourier-Image-Analysis#6]
https://github.com/turbomaze/JS-Fourier-Image-Analysis/blob/4131dfb5495ab3e93198208be29082dd3d42790d/js/main.js#L216

**Comment by naiteluo** [comment]
i dont get it, but curious about it.

**Comment by turbomaze** [comment]
This is just a dorky joke since the loop variable is `c`, so the increment is `c++`, which is the name of the C++ programming language.

**Comment by waldyrious** [comment]
@turbomaze perhaps the comma there is part of what makes this ambiguous, as it makes it seem like "RGB are the same" is part of the joke. Perhaps something like this would be less likely to generate confusion:

```js
for (var c = 0; c < 3; c++) { // RGB are the same. Also, lol c++ 
```

**Comment by naiteluo** [comment]
> This is just a dorky joke since the loop variable is `c`, so the increment is `c++`, which is the name of the C++ programming language.

I get it. lol. thx, funny!
